name: Git-Tag Name Actions
on: 
 push: 
   branches: [ master ]
 pull_request:
   branches: [ master ]
#    paths:
#      - '*'
jobs:
  Auto-tagging:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
      - name: Checkout branch master 
      - uses: actions/checkout@v3
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v1.2.3-0',
              sha: context.sha
            })
