# name: Git-Tag Version Actions
# on: 
#  push: 
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#    paths:
#      - 'deployment-1/**'
#      - 'deployment-2/**'
     

# jobs:
#   changes:
#     name: Detect Changes in folder
#     runs-on: ubuntu-latest
#     outputs:
#       names: ${{ steps.filter.outputs.changes }}

#     steps:
#     - uses: actions/checkout@v3
#     - name: Detect Changes
#       uses: dorny/paths-filter@v2
#       id: filter
#       with:
#         filters: |
#           deployment-1:
#             - 'deployment-1/**'
#           deployment-2:
#             - 'deployment-2/**'    
#   deploy:
#     needs: changes
#     if: ${{ needs.changes.outputs.names != '[]' }}
#     name:  ${{matrix.name}} - ${{ matrix.environment }}
#     runs-on: ubuntu-latest
#     strategy:
#       max-parallel: 1
#       matrix: 
#          name: ${{fromJson(needs.changes.outputs.names)}}
#          environment: [ prod ]    
#     defaults:
#       run:
#         shell: bash
#         working-directory: ${{ matrix.name }}
#     steps:
#       - uses: actions/checkout@v3
#         with:
#          fetch-depth: '0'

#       - name: Checking the folder name
#         run: |
#          echo "Running for folder ${{ matrix.name }}"   
#          chmod +x ./entrypoint.sh
#          ./entrypoint.sh  
#         #  chmod +x ./updatetags.sh
#         #  ./updatetags.sh
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     

  
    
    















